config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  	root to: 'tasklists#index'
  	resources :quotes, only: [:create, :destroy]
  	resources :bgimages, only: [:update]

	resources :tasklists, only: [:create, :destroy, :show] do
		resources :tasks, only: [:create, :destroy, :update, :edit]
	end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bgimage.rb
class Bgimage < ApplicationRecord


end

app/models/quote.rb
class Quote < ApplicationRecord
	
	validates :quot, presence: true
	validates :author, presence: true
	
end

app/models/task.rb
class Task < ApplicationRecord

	belongs_to :tasklist

	validates :tasktitle, presence: true
	validates :taskdesc, presence: true
	validates :taskstatus, presence: true
	validates :taskdue, presence: true

end

app/models/tasklist.rb
class Tasklist < ApplicationRecord

	has_many :tasks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
  
end

app/controllers/bgimages_controller.rb
class BgimagesController < ApplicationController

	def update
		img = Bgimage.find(params[:id])
		img_params = params[:bgimage].permit(:imgname)
		
		img.update(img_params)
		flash[:success] = "Background applied!"
		redirect_to root_path

	end


end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

	def create
		quo = params[:quote].permit(:quot, :author)
		quot = Quote.create(quo)
		flash[:success] = "New Quote created."
		redirect_to root_path
	end

	def destroy
		quote = Quote.find(params[:id])
		quote.destroy
		flash[:danger] = "Qoute Deleted."
		redirect_to root_path
	end

end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController

	def index
		@quot = Quote.all
		@quote = Quote.new

		@ins = @quot.sample
		@insquot = @ins.quot
		@insauth = @ins.author

		@bgimage = Bgimage.find_by(:id=>1)

		@list = Tasklist.all
		@tasklist = Tasklist.new

		@task = Task.new
		
	end

	def show
		@tasklist = Tasklist.find(params[:id])
		@task = @tasklist.tasks.build
	end

	def create
		tl = params[:tasklist].permit(:listname)
		Tasklist.create(tl)
		flash[:success] = "New list created."
		redirect_to root_path
	end

	def destroy
		list = Tasklist.find(params[:id])
		list.destroy
		flash[:danger] = "List Deleted."
		redirect_to root_path
	end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def create

		@tasklist = Tasklist.find(params[:tasklist_id])
		task_params = params.require(:task).permit(:tasktitle, :taskdesc, :taskstatus, :taskdue)
		@task = @tasklist.tasks.create(task_params)
		if @task.valid?
			flash[:success] = "New task created."
			redirect_to root_path
		else
			flash[:danger] = "Field(s) are blank."
			render "tasklists/show"
		end
	
	end

	def edit
		@tasklist = Tasklist.find(params[:tasklist_id])
		@task = @tasklist.tasks.find(params[:id])
	end

	def update 
		task_params = params[:task].permit(:tasktitle, :taskdesc, :taskstatus, :taskdue)
		tasklist = Tasklist.find(params[:tasklist_id])
		task = tasklist.tasks.find(params[:id])
		task.update(task_params)
		flash[:success] = "Task updated"
		redirect_to root_path
	end

	def destroy
		
		tasklists  = Tasklist.find(params[:tasklist_id])
		task = tasklists.tasks.find(params[:id])
		tasklists.tasks.delete(task)
		flash[:danger] = "Task Deleted."
		redirect_to root_path
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_message.html.erb
<div class="container" id="message" >
	 <% flash.each do |name, msg| %>
		    <div class="alert alert-<%= "#{name}" %> alert-dismissable fade in">
		  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		  <strong><%= "#{name}" %>!</strong> <%= "#{msg}" %>
		</div>
	  <% end %>

  </div>

app/views/layouts/_modals.html.erb
<!-- Quotes Modal -->
<div class="modal fade" id="quoteModal" tabindex="-1" role="dialog" aria-labelledby="quoteLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Inspirational Quotes</h4>
      </div>
      <div class="modal-body">
		<div class="tablecont">
	      	<table class="table table-hover table-responsive">
	      		<thead>
	      			<th width="300px">Quotes</th>
	      			<th>Author</th>
	      		</thead>
	      		<tbody>
	      			<% @quot.each do |q| %>
	      			<tr>
		      			<td width="300px"><%= q.quot %></td>
		      			<td><%= q.author %></td>
		      			<td><%= link_to 'Delete', quote_path(id:q.id), method: :delete, data: { confirm: "Are you sure?"}, class:"btn btn-danger btn-xs" %></td>
	      			</tr>
	      			<% end %>
	      		</tbody>
	      	</table>
        </div>
        <p><b>Add new Qoutes</b></p>
		<%= form_for @quote, url: quotes_path, method: :post do |f| %>

			<div class="form-group">
				<%= f.label :Quote %>
				<%= f.text_field :quot, class:"form-control", :required => true, autofocus: true %>
			</div>
			
			<div class="form-group">
				<%= f.label :author %>
				<%= f.text_field :author, class:"form-control", :required => true %>	
			</div>
			
      <div class="modal-footer">
        <%= f.submit "Add Quote", class:"btn btn-success" %>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		<% end %>
      </div>
    </div>
  </div>
</div>
</div>
<!-- End of Quotes Modal -->

<!-- New Task List Modal -->
<div class="modal fade" id="newlistModal" tabindex="-1" role="dialog" aria-labelledby="quoteLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Task Lists</h4>
      </div>
      <div class="modal-body">

		<table class="table table-hover">
			<thead>
				<th style="text-align: center;">List Name</th>
			</thead>
			<tbody>
				<% @list.each do |l| %>
				<tr>
					<td><%= l.listname %></td>
					<td><%= link_to 'New Task', tasklist_path(id: l.id), class: "btn btn-primary btn-xs" %></td>
					<td>
					<% if Task.where(tasklist_id: l.id).count == 0 %>
                        <%= link_to "Delete", tasklist_path(id:l.id), method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" %></td>
                     <% else %>
                        <button class="btn btn-danger btn-xs" data-toggle="tooltip" data-placement="top" title="There are task(s) to be done." disabled="true">Delete</button>
                    <% end %>
					
				</tr>
				<% end %>
			</tbody>
		</table>
		<hr>
		<%= form_for @tasklist, url: tasklists_path, method: :post do |f| %>
			<%= f.label 'New List name:' %>
			<div class="input-group">
				<%= f.text_field :listname, class: "form-control" %>
				<div class="input-group-btn">
					<%= f.submit 'Create', class: "btn btn-success" %>
				</div>
			</div>
		<% end %>
      <div class="modal-footer">
		<!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button> -->
      </div>
    </div>
  </div>
</div>
</div>
<!-- End of New Task List Modal -->

<!-- Task Modal -->
<div class="modal fade" id="taskModal" tabindex="-1" role="dialog" aria-labelledby="quoteLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Task</h4>
      </div>
      <div class="modal-body">
		
		<h4>Select Task List:</h4>

		<div class="form-group">
			<select class="form-control" id="sel1">
				<% @list.each do |l| %>
				<%= options_for_select([[l.listname, l.id]]) %>
				<% end %>
			</select>
		</div>

			
		
        	
      <div class="modal-footer">
        
        <button type="button" class="btn btn-success" data-toggle="modal" data-target="#taskModal">Create</button>
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		
      </div>
    </div>
  </div>
</div>
</div>
<!-- End of Task Modal -->

<!-- Bg modal -->
<div class="modal fade" id="bgModal" tabindex="-1" role="dialog" aria-labelledby="quoteLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Background</h4>
      </div>
      <div class="modal-body">
		
        <div class="imgThumb">
	        
	        
	        <%= form_for @bgimage, url: bgimage_path(id:1), method: :put do |f| %>
				<%= f.hidden_field :imgname, value: "cover4" %>
				<%= image_submit_tag 'cover4', class:"img-responsive img-thumbnail" %>
			<% end %>
	        
			<%= form_for @bgimage, url: bgimage_path(id:1), method: :put do |f| %>
				<%= f.hidden_field :imgname, value: "cover3" %>
				<%= image_submit_tag 'cover3', class:"img-responsive img-thumbnail" %>
			<% end %>
			
			<%= form_for @bgimage, url: bgimage_path(id:1), method: :put do |f| %>
				<%= f.hidden_field :imgname, value: "cover2" %>
				<%= image_submit_tag 'cover2', class:"img-responsive img-thumbnail" %>
			<% end %>

			<%= form_for @bgimage, url: bgimage_path(id:1), method: :put do |f| %>
				<%= f.hidden_field :imgname, value: "cover" %>
				<%= image_submit_tag 'cover', class:"img-responsive img-thumbnail" %>
			<% end %>

			<%= form_for @bgimage, url: bgimage_path(id:1), method: :put do |f| %>
				<%= f.hidden_field :imgname, value: "cover5" %>
				<%= image_submit_tag 'cover5', class:"img-responsive img-thumbnail" %>
			<% end %>

			<%= form_for @bgimage, url: bgimage_path(id:1), method: :put do |f| %>
				<%= f.hidden_field :imgname, value: "cover6" %>
				<%= image_submit_tag 'cover6', class:"img-responsive img-thumbnail" %>
			<% end %>

			<%= form_for @bgimage, url: bgimage_path(id:1), method: :put do |f| %>
				<%= f.hidden_field :imgname, value: "cover7" %>
				<%= image_submit_tag 'cover7', class:"img-responsive img-thumbnail" %>
			<% end %>

			<%= form_for @bgimage, url: bgimage_path(id:1), method: :put do |f| %>
				<%= f.hidden_field :imgname, value: "cover8" %>
				<%= image_submit_tag 'cover8', class:"img-responsive img-thumbnail" %>
			<% end %>


		</div>

      <div class="modal-footer">
        
		<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		
      </div>
    </div>
  </div>
</div>
</div>
<!-- End of Bg Modal -->

app/views/layouts/_nav.html.erb
<!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Task Manager
                    </a>
                </li>
                <li>
                    <a href="#" data-toggle="modal" data-target="#newlistModal">Tasks</a>
                </li>
                <li>
                    <a href="#">Archives</a>
                </li><br>
                <li>
                    <a href="#">Settings</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

app/views/layouts/_quotes.html.erb
<div class="pull-right bg-danger" id="insBox">
	<p><i>"<%= @insquot %>"</i> <br><small class="pull-right">- <%= @insauth %><button style="margin-left: 3px; color:gray;" class="btn btn-primary btn-xs btn-link pull-right" data-toggle="modal" data-target="#quoteModal"><i class="glyphicon glyphicon-plus"></i></button></small></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    
    <style>
      body {
        overflow-x: hidden;

           /*background: url(<% @bgimg %>) center center no-repeat;*/
          background-image: url( <%= asset_path Bgimage.find_by(id:1).imgname %> );
          background-size: cover;
          background-repeat: no-repeat;
          background-position: center;
          box-shadow: inset 0 0 100px #000;
      }
    </style>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
  
    	 <%= yield %>
       
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
        $("#menuButt").toggleClass("fa fa-list fa-2x").toggleClass("fa fa-times fa-2x");

    });
    $(".alert").fadeTo(2000, 500).fadeOut(500, function(){
               $(".alert").fadeOut(500);
                }); 

    </script>
  </body>
</html>

app/views/tasklists/index.html.erb
<div id="wrapper">
        
        <%= render 'layouts/nav' %>
        
            <div id="page-content-wrapper">
            <div class="container-fluid">
              <a href="#menu-toggle" class="btn btn-warning" id="menu-toggle"><span id="menuButt" class="fa fa-list fa-2x"></span></a>
<%= render 'layouts/quotes' %>
<%= render 'layouts/message' %>
<div class="container" id="taskCont">
	<div class="panel">
		<div class="panel-heading" style="background-color: #FF7043;">
			<h1 class="panel-title" style="color: white;"><i class="fa fa-calendar" aria-hidden="true"></i> Tasks</h1>
		</div>
		<div id="accCont">
		<div class="panel-group" id="accordion">

                <% @list.each do |l| %>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>
                            <a data-toggle="collapse" data-parent="#accordion" href="#<%= l.id %>"><span class="fa fa-tasks">
                            </span> <%= l.listname %></a>
                        </h4>
                    </div>
                    <div id="<%= l.id %>" class="panel-collapse collapse">
                        <table class="table table-hover">
                        	<thead>
                        		<th>Title</th>
                        		<th>Due Date</th>
                        		<th>Status</th>
                        	</thead>
                        	<tbody>
                                <% l.tasks.each do |t| %>
                        		<tr>
                        			<td><%= t.tasktitle %></td>
                        			<td><%= t.taskdue %></td>
                        			<td> <span class="label label-<%= t.taskstatus %>">
                                    <%= if t.taskstatus == 'danger' then 'Incomplete' end %>
                                    <%= if t.taskstatus == 'warning' then 'In Progress' end %>
                                    <%= if t.taskstatus == 'success' then 'Complete' end%></span> </td>
                        			<td> <%= link_to 'View', edit_tasklist_task_path(tasklist_id:l.id, id:t.id), class: "btn btn-info btn-xs" %></td>
                        			<td><%= link_to "Delete", tasklist_task_path(tasklist_id:l.id, id:t.id) , method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-danger btn-xs" %></td>
                        		</tr>
                                <% end %>
                        	</tbody>
                        </table>
                    </div>
                </div>
				<% end %>

      <%= render 'layouts/modals' %>
       </div> 
        </div>
    </div></div></div></div>
    <div id="bgChange"><button class="btn btn-default " data-toggle="modal" data-target="#bgModal"><span class="fa fa-picture-o"></span></button></div>

app/views/tasklists/show.html.erb
<div class="msgg"><%= render 'layouts/message' %></div>

<div class="container taskShow">
	<div class="panel">
		<div class="panel-heading" style="background-color: #FF7043;">
			<h1 class="panel-title" style="color: white;"><i class="fa fa-calendar" aria-hidden="true"></i> Task for <%= @tasklist.listname %></h1>
		</div><br>
		
		<div class="panel-body">
			<h2> </h2>
			<%= form_for @task, url: tasklist_tasks_path(tasklist_id: @tasklist.id), method: :post do |f| %>
				
				<%= f.label 'Title' %>
				<%= f.text_field :tasktitle, class: "form-control" %>
				<%= f.label 'Task Description' %>
				<%= f.text_area :taskdesc, class: "form-control" %> <br>
				<%= f.label 'Task Status' %>
				<div class="row">
					<div class="col-md-6">
						<%= f.radio_button(:taskstatus, "danger") %>
						<%= f.label(:taskstatus_danger, "Incomplete") %>
						<%= f.radio_button(:taskstatus, "warning") %>
						<%= f.label(:taskstatus_warning, "In-Progress") %>
						<%= f.radio_button(:taskstatus, "success") %>
						<%= f.label(:taskstatus_success, "Complete") %>
					</div>
					<div class="col-md-6">
						<%= f.label 'Task Due' %>
						<%= f.text_field :taskdue, :data => { :provide => :datepicker } %>
					</div>
				</div>
				<hr>
				<%= link_to 'Back', root_path, class: "btn btn-default" %>
				<%= f.submit 'submit', class: "btn btn-success pull-right" %>

			<% end %>
		</div>
	</div>
</div>

app/views/tasks/edit.html.erb
<div class="container taskShow">
	<div class="panel">
		<div class="panel-heading" style="background-color: #FF7043;">
			<h1 class="panel-title" style="color: white;"><i class="fa fa-calendar" aria-hidden="true"></i> Task for <%= @tasklist.listname %></h1>
		</div><br>
		
		<div class="panel-body">
			<h2> </h2>
			<%= form_for @task, url: tasklist_task_path(tasklist_id: @tasklist.id), method: :put do |f| %>
				
				<%= f.label 'Title' %>
				<%= f.text_field :tasktitle, class: "form-control" %>
				<%= f.label 'Task Description' %>
				<%= f.text_area :taskdesc, class: "form-control" %> <br>
				<%= f.label 'Task Status' %>
				<div class="row">
					<div class="col-md-6">
						<%= f.radio_button(:taskstatus, "danger") %>
						<%= f.label(:taskstatus_danger, "Incomplete") %>
						<%= f.radio_button(:taskstatus, "warning") %>
						<%= f.label(:taskstatus_warning, "In-Progress") %>
						<%= f.radio_button(:taskstatus, "success") %>
						<%= f.label(:taskstatus_success, "Complete") %>
					</div>
					<div class="col-md-6">
						<%= f.label 'Task Due' %>
						<%= f.text_field :taskdue, :data => { :provide => :datepicker } %>
					</div>
				</div>
				<hr>
				<%= link_to 'Back', root_path, class: "btn btn-default" %>
				<%= f.submit 'submit', class: "btn btn-success pull-right" %>

			<% end %>
		</div>
	</div>
</div>